package vistas;

import controladores.GrafoControlador;
import java.awt.Graphics;
import java.awt.Graphics2D;
import javax.swing.JFrame;

public class Grafo extends javax.swing.JFrame {

   
    public Grafo() {
        initComponents();
        //setSize(1000, 615);
        setResizable(false);
        setLocationRelativeTo(null);      
        this.repaint();
        this.setVisible(true);
        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelCanvas = new javax.swing.JPanel();
        jPanelBoton = new javax.swing.JPanel();
        btn_grafo_close = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelCanvas.setBackground(new java.awt.Color(255, 255, 255));
        jPanelCanvas.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Grafo creado dinámicamente - Ordenado por Page Rank(R)", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        jPanelCanvas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelBoton.setBackground(new java.awt.Color(255, 255, 204));
        jPanelBoton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_grafo_close.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_grafo_close.setText("Cerrar");
        btn_grafo_close.setSelected(true);
        btn_grafo_close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_grafo_closeActionPerformed(evt);
            }
        });
        jPanelBoton.add(btn_grafo_close, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, 120, 35));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelCanvas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelBoton, javax.swing.GroupLayout.DEFAULT_SIZE, 946, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelCanvas, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelBoton, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_grafo_closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_grafo_closeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_grafo_closeActionPerformed

 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Grafo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Grafo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Grafo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Grafo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Grafo().setVisible(true);
            }
        });
    }
    // Sobrescribir el método paint para dibujar el grafo en el canvas
    @Override
    public void paint(Graphics g) {
        super.paint(g);
        Graphics2D g2d = (Graphics2D) g;
        // Llamar al método dibujarGrafo del controlador para que dibuje el grafo en el canvas
        GrafoControlador grafoControl = new GrafoControlador(this);
        grafoControl.dibujarGrafo(g2d);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_grafo_close;
    public javax.swing.JPanel jPanelBoton;
    public javax.swing.JPanel jPanelCanvas;
    // End of variables declaration//GEN-END:variables
}
